binary_sensor:
  - platform: ping
    host: 192.168.1.10
    name: PING Core Switch
    count: 3
    scan_interval: 10

  - platform: ping
    host: 192.168.1.1
    name: PING Local Router
    count: 3
    scan_interval: 10

  - platform: ping
    host: 192.168.100.1
    name: PING Cable Modem
    count: 3
    scan_interval: 10

  - platform: ping
    host: 1.1.1.1
    name: PING Cloudflare
    count: 3
    scan_interval: 60

  - platform: ping
    host: 8.8.8.8
    name: PING Google
    count: 3
    scan_interval: 60

  - platform: command_line
    command: 'nslookup google.com 192.168.1.1 >> /dev/null && echo pass || echo fail'
    payload_on: pass
    payload_off: fail
    name: DNS Local Nameserver
    scan_interval: 10
    command_timeout: 30
    device_class: connectivity

  - platform: command_line
    command: 'nslookup google.com 1.1.1.1 >> /dev/null && echo pass || echo fail'
    payload_on: pass
    payload_off: fail
    name: DNS Cloudflare Nameserver
    scan_interval: 60
    command_timeout: 30
    device_class: connectivity

  - platform: command_line
    command: 'nslookup google.com 8.8.8.8 >> /dev/null && echo pass || echo fail'
    payload_on: pass
    payload_off: fail
    name: DNS Google Nameserver
    scan_interval: 60
    command_timeout: 30
    device_class: connectivity
